/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wpsistemas.view;


import br.com.wpsistemas.model.dao.entitades.Usuario;
import br.com.wpsistemas.tableModel.UsuarioColumnModel;
import br.com.wpsistemas.tableModel.UsuarioTableModel;
import java.awt.Dimension;
import java.awt.FontMetrics;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.util.List;

/**
 *
 * @author wender
 */
public class UsuarioICons extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioICons
     */
    public UsuarioICons() {
        initComponents();
        this.centralizarTela();
        statusBotoes(true, false, true );
        this.formatarColumnJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxfPesquisarValor = new javax.swing.JTextField();
        jCboPesquisarPor = new javax.swing.JComboBox<>();
        jBtnPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTbUsuario = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        jBtnNovo = new javax.swing.JButton();
        jBtnEditar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jBtnFechar = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("Consultar Pais");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Pesquisar"));
        jPanel1.setName(""); // NOI18N

        jLabel1.setText("Por");

        jCboPesquisarPor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NOME", "CODIGO" }));

        jBtnPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/pesquisar.png"))); // NOI18N
        jBtnPesquisar.setToolTipText("Pesquisar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCboPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxfPesquisarValor, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jBtnPesquisar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxfPesquisarValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCboPesquisarPor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTbUsuario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Código", "Nome", "Email", "User Name"
            }
        ));
        jScrollPane1.setViewportView(jTbUsuario);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jBtnNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/novo.png"))); // NOI18N
        jBtnNovo.setToolTipText("Novo");
        jBtnNovo.setActionCommand("novoPais");
        jBtnNovo.setFocusable(false);
        jBtnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnNovo);

        jBtnEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/editdocuments.png"))); // NOI18N
        jBtnEditar.setToolTipText("Editar");
        jBtnEditar.setFocusable(false);
        jBtnEditar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnEditar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnEditar);
        jToolBar1.add(filler1);

        jBtnFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/exit.png"))); // NOI18N
        jBtnFechar.setToolTipText("Fechar");
        jBtnFechar.setFocusable(false);
        jBtnFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnFechar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jBtnEditar;
    private javax.swing.JButton jBtnFechar;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JComboBox<String> jCboPesquisarPor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTbUsuario;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jTxfPesquisarValor;
    // End of variables declaration//GEN-END:variables

    private UsuarioIFrm usuarioFrm;

    public void centralizarTela() {
        Dimension tamanhoTela = getToolkit().getScreenSize();
        Dimension tamanho = getSize();
        setLocation((tamanhoTela.width - tamanho.width) / 2, 20 );//(tamanhoTela.height - tamanho.height) / 2);
    }

    public void setActionListenerJbtnNovo(ActionListener actionListener) {
        this.jBtnNovo.addActionListener(actionListener);
    }
    
    public void setActionListenerJbtnEditar(ActionListener actionListener) {
        this.jBtnEditar.addActionListener(actionListener);
    }

    public void setActionListenerJbtnFechar(ActionListener actionListener) {
        this.jBtnFechar.addActionListener(actionListener);
    }

    public void setActionListenerJbtnPesquisar(ActionListener actionListener) {
        this.jBtnPesquisar.addActionListener(actionListener);
    }
    
    public void setMouseListenerJTblUsuario(MouseAdapter mouseAdapter) {
        jTbUsuario.addMouseListener(mouseAdapter);
    }
    
     private void formatarColumnJTable() {
        FontMetrics fm = jTbUsuario.getFontMetrics(jTbUsuario.getFont());
        jTbUsuario.setColumnModel(new UsuarioColumnModel(fm));
    }
    
    UsuarioTableModel model = new UsuarioTableModel();
    public void setListaUsuario(List<Usuario> listaUsuario) {        
        this.jTbUsuario.setModel(model);        
        model.addListaDeUsuario(listaUsuario);
        this.formatarColumnJTable();
    }
    
    public Usuario getUsuarioSelecionado() {
        return model.getUsuario(jTbUsuario.getSelectedRow());
    }
    
    public String[] getParametroPesquisa() {
        String param[] = new String[2];
        param[0] = (String)jCboPesquisarPor.getSelectedItem();
        param[1] = jTxfPesquisarValor.getText().toUpperCase();
        return param;
    }
    
    /**
     * 
     * @param novo
     * @param editar
     * @param fechar 
     * Ativa e desativa os Botões 
     */
    public void statusBotoes(Boolean novo, Boolean editar, Boolean fechar) {
        jBtnNovo.setEnabled(novo);
        jBtnEditar.setEnabled(editar);
        jBtnFechar.setEnabled(fechar);
    }

}
