/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.wpsistemas.view;


import br.com.wpsistemas.model.dao.entitades.Usuario;
import br.com.wpsistemas.uteis.Uteis;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;

/**
 *
 * @author wender
 */
public class UsuarioIFrm extends javax.swing.JInternalFrame {

    /**
     * Creates new form UsuarioIFrm
     */
    public UsuarioIFrm() {
        initComponents();
        this.centralizarTela();
        this.statusBotoes(Boolean.FALSE, Boolean.TRUE, Boolean.FALSE, Boolean.TRUE, Boolean.TRUE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        jBtnNovo = new javax.swing.JButton();
        jBtnSalvar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jBtnPesquisar = new javax.swing.JButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        jBtnFechar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTxfCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxfNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTxfEmail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTxfUserName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jPwfSenha = new javax.swing.JPasswordField();

        setIconifiable(true);
        setTitle("Cadastro de Pais");

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        jBtnNovo.setText("Novo");
        jBtnNovo.setToolTipText("Novo");
        jBtnNovo.setFocusable(false);
        jBtnNovo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnNovo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnNovo);

        jBtnSalvar.setText("Salvar");
        jBtnSalvar.setToolTipText("Salvar");
        jBtnSalvar.setFocusable(false);
        jBtnSalvar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnSalvar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnSalvar);

        jBtnExcluir.setText("Apagar");
        jBtnExcluir.setToolTipText("Excluir");
        jBtnExcluir.setFocusable(false);
        jBtnExcluir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnExcluir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnExcluir);

        jBtnPesquisar.setText("Pesquisar");
        jBtnPesquisar.setToolTipText("Pesquisar");
        jBtnPesquisar.setFocusable(false);
        jBtnPesquisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnPesquisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jBtnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisarActionPerformed(evt);
            }
        });
        jToolBar1.add(jBtnPesquisar);
        jToolBar1.add(filler1);

        jBtnFechar.setText("Fechar");
        jBtnFechar.setToolTipText("Fechar");
        jBtnFechar.setFocusable(false);
        jBtnFechar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jBtnFechar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar1.add(jBtnFechar);

        jLabel1.setText("Código");

        jTxfCodigo.setEditable(false);

        jLabel2.setText("Nome");

        jLabel3.setText("Email");

        jTxfEmail.setColumns(3);

        jLabel4.setText("User Name");

        jLabel5.setText("Senha");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTxfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxfNome, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
                    .addComponent(jTxfEmail)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jPwfSenha, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                        .addComponent(jTxfUserName, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTxfCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTxfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTxfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTxfUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jPwfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBtnPesquisarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnFechar;
    private javax.swing.JButton jBtnNovo;
    private javax.swing.JButton jBtnPesquisar;
    private javax.swing.JButton jBtnSalvar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPwfSenha;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField jTxfCodigo;
    private javax.swing.JTextField jTxfEmail;
    private javax.swing.JTextField jTxfNome;
    private javax.swing.JTextField jTxfUserName;
    // End of variables declaration//GEN-END:variables

    public void centralizarTela() {
        Dimension tamanhoTela = getToolkit().getScreenSize();
        Dimension tamanho = getSize();
        setLocation((tamanhoTela.width - tamanho.width) / 2, 20);
    }

    public void setActionListenerJbtnNovo(ActionListener actionListener) {
        this.jBtnNovo.addActionListener(actionListener);
    }

    public void setActionListenerJbtnSalvar(ActionListener actionListener) {
        this.jBtnSalvar.addActionListener(actionListener);
    }

    public void setActionListenerJbtnExcluir(ActionListener actionListener) {
        this.jBtnExcluir.addActionListener(actionListener);
    }

    public void setActionListenerJbtnPesquisar(ActionListener actionListener) {
        this.jBtnPesquisar.addActionListener(actionListener);
    }

    public void setActionListenerJbtnFechar(ActionListener actionListener) {
        this.jBtnFechar.addActionListener(actionListener);
    }

    private Usuario usuario;

    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
        if (this.usuario.getId() != null) {
            jTxfCodigo.setText(String.valueOf(this.usuario.getId()));
        } else {
            jTxfCodigo.setText("");
        }
        jTxfNome.setText(this.usuario.getNome());        
        jTxfEmail.setText(this.usuario.getEmail());
        jTxfUserName.setText(this.usuario.getUserName());
        jPwfSenha.setText(this.usuario.getSenha());
    }

    public Usuario getUsuario() {
        Boolean campoVazio = false;
        String campo = "";        
        if (!jTxfNome.getText().equals("")) {
            this.usuario.setNome(jTxfNome.getText().toUpperCase());
        } else {
            campo += " Nome, ";
            campoVazio = Boolean.TRUE;
        }
        if (!jTxfEmail.getText().equals("")) {
            this.usuario.setEmail(jTxfEmail.getText().toUpperCase());
        } else {
            campo += " Email, ";
            campoVazio = Boolean.TRUE;
        }
        if (!jTxfUserName.getText().equals("")) {
            this.usuario.setUserName(jTxfUserName.getText());
        } else {
            campo += " User Name, ";
            campoVazio = Boolean.TRUE;
        }
        
        if (!jPwfSenha.getPassword().equals("")) {
            this.usuario.setSenha(Uteis.parseSenha(jPwfSenha.getPassword()));
        } else {
            campo += " Senha, ";
            campoVazio = Boolean.TRUE;
        }
        
        
        if (campoVazio) {
            JOptionPane.showMessageDialog(null, "Informe: " + campo, "Atenção", JOptionPane.INFORMATION_MESSAGE);
            return null;
        } else {
            return this.usuario;
        }
    }

    /**
     *
     * @param novo
     * @param salvar
     * @param excluir
     * @param pesquisar
     * @param fechar Ativa e desativa os Botões
     */
    public void statusBotoes(Boolean novo, Boolean salvar, Boolean excluir, Boolean pesquisar, Boolean fechar) {
        jBtnNovo.setEnabled(novo);
        jBtnSalvar.setEnabled(salvar);
        jBtnExcluir.setEnabled(excluir);
        jBtnPesquisar.setEnabled(pesquisar);
        jBtnFechar.setEnabled(fechar);
    }
}
